services:
  server:
    build:
      context: ./
      dockerfile: ./KotlinServer/Dockerfile
    ports:
      - "5000:5000"

  client:
    build:
      context: ./
      dockerfile: ./PythonClient/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - server
