services:
  server:
    build:
      context: ./
      dockerfile: ./KotlinServer/Dockerfile
    ports:
      - "8080:8080"

  client:
    build:
      context: ./
      dockerfile: ./PythonClient/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - server
